### ISSUE TITLE
USB HID

### ISSUE THREAD

**Issue by prosper00** [Jerther/arduino-sidewinder-gp#1]
cool project. i just bought one of these gamepads at a thrift store, and ill probably borrow some of your code. Ive just completed a similar adapter for the gravis gamepad pro, which is quite similar. If you use an arduino leonardo, you can emulate a keyboard directly, and do without the python script

https://github.com/prosper00/GRiP-duino

**Comment by Jerther** [comment]
Yeah, the leonardo is nice and that is what I have planned to go with if I ever turn this project into one I actually use ;)

I hope you have fun with the Sidewinder. It's a really nice device, but the Sidewinder protocol is another story ;) The GP protocol is not as bad as the joystick's though. It's quite simpler.

Nice work on the Gravis GPP!
